name: Build

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  emscripten:
    name: Emscripten
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python (required for Emscripten)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
        shell: bash

      - name: Build with Emscripten
        run: |
          source emsdk/emsdk_env.sh
          emcmake cmake . -B emscripten-build
          cmake --build emscripten-build --config=Release
        shell: bash
  
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
    
      - name: Build
        run: |
          cmake . -B build -DCMAKE_BUILD_TYPE:String=Release
          cmake --build build --config Release
        shell: bash

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build with Emscripten
        run: |
          cmake . -B build -DCMAKE_BUILD_TYPE:String=Release
          cmake --build build --config Release
    
      