name: Emscripten Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python (required for Emscripten)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
        shell: bash

      - name: Build with Emscripten
        run: |
          source emsdk/emsdk_env.sh
          emcmake cmake . -B emscripten-build -DCMAKE_BUILD_TYPE:String=Debug
          cmake --build emscripten-build --config Debug
        shell: bash

      - name: Deploy Main Demo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDR }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          source: "emscripten-build/demo.html,emscripten-build/demo.js,emscripten-build/demo.wasm,emscripten-build/demo.data"
          target: ${{ secrets.REMOTE_SERVER_DIRECTORY }}
          strip_components: 1

      - name: Deploy Waveform Demo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDR }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          source: "emscripten-build/demo_waveform.html,emscripten-build/demo_waveform.js,emscripten-build/demo_waveform.wasm,emscripten-build/demo_waveform.data"
          target: ${{ secrets.REMOTE_SERVER_DIRECTORY }}
          strip_components: 1

      - name: Deploy Synthesis Demo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDR }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          source: "emscripten-build/demo_synthesis.html,emscripten-build/demo_synthesis.js,emscripten-build/demo_synthesis.wasm,emscripten-build/demo_synthesis.data"
          target: ${{ secrets.REMOTE_SERVER_DIRECTORY }}
          strip_components: 1
