name: Emscripten Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python (required for Emscripten)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
        shell: bash

      - name: Build with Emscripten
        run: |
          source emsdk/emsdk_env.sh
          emcmake cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --config Debug
        shell: bash

      - name: Deploy Main Demo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDR }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          source: "build/demos/demo.html,build/demos/demo.js,build/demos/demo.wasm,build/demos/demo.data"
          target: ${{ secrets.REMOTE_SERVER_DIRECTORY }}
          strip_components: 2

      - name: Deploy Waveform Demo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDR }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          source: "build/demos/demo_waveform.html,build/demos/demo_waveform.js,build/demos/demo_waveform.wasm,build/demos/demo_waveform.data"
          target: ${{ secrets.REMOTE_SERVER_DIRECTORY }}
          strip_components: 2

      - name: Deploy Synthesis Demo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDR }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          source: "build/demos/demo_synthesis.html,build/demos/demo_synthesis.js,build/demos/demo_synthesis.wasm,build/demos/demo_synthesis.data"
          target: ${{ secrets.REMOTE_SERVER_DIRECTORY }}
          strip_components: 2

      - name: Deploy Spatialization Demo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDR }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          source: "build/demos/demo_spatialization.html,build/demos/demo_spatialization.js,build/demos/demo_spatialization.wasm,build/demos/demo_spatialization.data"
          target: ${{ secrets.REMOTE_SERVER_DIRECTORY }}
          strip_components: 2

