name: Emscripten Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python (required for Emscripten)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
        shell: bash

      - name: Build with Emscripten
        run: |
          source emsdk/emsdk_env.sh
          emcmake cmake . -B emscripten-build
          cmake --build emscripten-build --config=Release
        shell: bash
