name: Emscripten Build

on:
  push:
    branches:
      - main
      - test-branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python (required for Emscripten)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
        shell: bash

      - name: Configure the build
        run: |
          cd demo
          make emscripten
        shell: bash

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.10.1
        with:
          ssh-private-key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
- name: Upload files to server
  run: |
    ssh-keyscan -H ${{ secrets.REMOTE_SERVER_ADDR }} >> ~/.ssh/known_hosts
    scp -P ${{ secrets.REMOTE_SERVER_PORT }} -r demos ${{ secrets.REMOTE_SERVER_USER }}@${{ secrets.REMOTE_SERVER_ADDR }}:${{ secrets.REMOTE_SERVER_DIRECTORY }}/




